package com.pratiksha.demo.utility;

public class CommonProperties {
    public  final static String SUCCESS_TYPE="Success" ;
    public  final static String ERROR_TYPE="Error" ;
    public  final static String SUCCESS_SAVE_MESSAGE="Information saved successfully" ;
    public  final static String SUCCESS_UPDATE_MESSAGE="Information updated successfully" ;
    public  final static String SUCCESS_DELETE_MESSAGE="Information deleted successfully" ;
    public  final static String NO_DATA_FOUND="Data not found " ;
    public  final static String PROBLEM_ERROR="Some Problem happen!!" ;
    public final static String USER_ACTIVATE="User Activated Successfully";
    public final static String USER_DEACTIVATE="User Is Deactivate";
    public final static String USER_SUBJECT="Activation Link!!";
    public final static String USER_TEXT="This is Autogenerated Mail .Please Do Not Reply";
    public final static String USER_ACTIVATION_MAIL="Activation Mail Sent!!";
    public final static String USER_OTP="OTP Sent !!";
    public final static String OTP_ACTIVATION="Activation By OTP";
    public final static String PASSWORD_RESET="Password Reset Successfully";
    public final static String ACCOUNT_CREATED="Account Created Successfully";

   //public final static String PASSWORD_RESET="Password Reset Successfully";

}
